# SITE CONFIGURATION
baseurl: ""
url: "https://kaspy.cf"
title: KASPY # site's title
description: "Группа компаний" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: KASPY группа компаний # blog's title
  avatar: assets/ico.png
  favicon: assets/ico.png
  gravatar: temirkhan.imangali@gmail.com # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <h2> ТОО "KASPY" </h2>
     <p> лидер отечественного рынка качественных товаров по объемам выпуска продукции, технологиям, дистрибуции. </p>
  header_text_feature_image: assets/img/pexel/architecture-blur-building-257636.jpg
  footer_text: >	    
   <a href="tel:+77784974444">+7(778)-497-44-44 &ensp; </a>
   <a href="tel:+77021110795">+7(702)-111-07-95 <br> </a>
   © <a href="https://vk.com/id212041065">Imangali Temirkhan</a> 2018

  # Icons
  rss: false  # Make sure you created a feed.xml with feed.xml layout
  email_address: temirkhan.imangali@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: profile.php?id=100009475494278&ref=bookmarks
  flickr:
  gitlab:
  github: 
  google_plus:
  instagram: nurzhan_mr/
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: true
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin:
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: false
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  #sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
